[package]
name = "gluon"
version = "0.0.0"
publish = false
edition.workspace = true

[dependencies]
gluon-compose = { path = "../gluon-compose" }
gluon-core = { path = "../gluon-core" }
gluon-font = { path = "../gluon-font" }
gluon-layout = { path = "../gluon-layout" }
gluon-paint = { path = "../gluon-paint" }
gluon-style = { path = "../gluon-style" }
gluon-text = { path = "../gluon-text" }
gluon-tree = { path = "../gluon-tree" }
gluon-wgpu = { path = "../gluon-wgpu" }
